#=================
# postgreSQL 연결
#=================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proj
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      show-sql: false

#=================
# Server 설정
#=================
server:
  port: 8443 #톰캣-보안적용
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-password: 12345678
    key-store-type: PKCS12
    key-alias: tomcat
    key-store-password: 12345678





